<a href="https://colab.research.google.com/github/abbu1809/ML-Lab/blob/main/Copy_of_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Tutorial

This notebook provides an introduction to NumPy, the fundamental package for scientific computing with Python. It covers basic array creation, manipulation, random number generation, indexing, slicing, arithmetic operations, broadcasting, and linear algebra operations.

In [1]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


## 1. Array Creation and Basic Properties

This section demonstrates how to create NumPy arrays from Python lists and explores basic array properties such as type, dimension, size, shape, and data type. It also shows how to generate sequences of numbers using `np.arange` and `np.linspace`.

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [3]:
print("A series of numbers:",np.arange(5,16)) # A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [4]:
print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [5]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [6]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [7]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,21))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


## 2. Special Arrays: Zeroes, Ones, Empty, and Identity Matrices

This section demonstrates how to create special types of arrays, including arrays filled with zeros, ones, or uninitialized (empty) values, and identity matrices, which are crucial in linear algebra.

In [ ]:
print('Type/Class of this object:',type(arr)) # Get the type of the array object
print('Here is the vector\n--------------------\n',arr)

# Create a 2D array (matrix) from a list of lists
print('Type/Class of this object:',type(mat))
print('Here is the matrix\n----------\n',mat,'\n----------')
print('Dimension of this matrix: ',mat.ndim,sep='') # ndim gives the dimension, 2 for a matrix, 1 for a vector
print('Size of this matrix: ', mat.size,sep='') # size gives the total number of elements
print('Shape of this matrix: ', mat.shape,sep='') # shape gives the number of elements along each axes (dimension)
print('Data type of this matrix: ', mat.dtype,sep='') # dtype gives the data type contained in the array

# Generate a sequence of numbers using np.arange
print('A series of numbers:',np.arange(5,16)) # A series of numbers from low to high
print('Numbers spaced apart by 2:',np.arange(0,11,2)) # Numbers spaced apart by 2
print('Numbers spaced apart by float:',np.arange(0,11,2.5)) # Numbers spaced apart by 2.5
print('Every 5th number from 50 in reverse order\n',np.arange(50,-1,-5))

# Generate linearly spaced numbers using np.linspace
print('21 linearly spaced numbers between 1 and 5\n--------------------------------------------')
print(np.linspace(1,5,21))

# Zeroes, Ones, empty, and Identity **matriX**

> Indented block



In [8]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]
Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print("Vector of ones\n---------------------")
print(np.ones(5))
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]
Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [10]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [11]:
mat1 = np.eye(4)
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3. Random Number Generation

NumPy provides functions to generate arrays filled with random numbers from various distributions, useful for simulations and statistical analyses.

In [ ]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5)) # Creates a 1D array of 5 zeros
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Creates a 3x4 2D array of zeros (note the tuple for shape)

print("Vector of ones\n---------------------")
print(np.ones(5)) # Creates a 1D array of 5 ones
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Creates a 5x2 2D array of ones
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5))) # Creates a 3x5 matrix filled with 5s by multiplying an array of ones by 5

print("Empty matrix\n--------------\n", np.empty((3,5))) # Creates an array without initializing its entries (may contain arbitrary values)

mat1 = np.eye(4) # Creates a 4x4 identity matrix
print("Identity matrix of dimension", mat1.shape)
print(mat1)

In [12]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

Random number generation (from Uniform distribution)
[[0.40917942 0.67025957 0.48841039]
 [0.70839642 0.45457381 0.5967424 ]]


In [13]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.00512843 -0.31123995 -0.56708715]
 [ 0.68600284 -0.06924366  1.51491787]
 [-0.78024243 -0.72559188  0.20133544]
 [ 0.15327672  0.29523242  1.16515041]]


In [14]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [22 52 36 31 98 21 51 45 59 12]

Random integer matrix
[[61  9 96 46]
 [78 74 62 75]
 [54  4 21 39]
 [58 84 36 99]]

20 samples drawn from a dice throw: [1 5 5 1 5 4 5 2 5 4 1 5 3 6 5 1 3 2 5 3]


## 4. Reshaping, Min, Max, and Sort

This section covers methods for changing the shape of arrays, finding minimum and maximum values, and sorting arrays along different axes.

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1 (uniform distribution)

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3)) # 4 by 3 matrix with random numbers from a standard normal distribution

print("Random integer vector:",np.random.randint(1,100,10)) # randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) # randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw (integers from 1 to 6)

# Reshaping, min, max, **sort**

In [15]:
import numpy as np
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)

A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))

M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)

a looks like
 -------------------- 
 [77 86 23 38 32 86 75 71 64  1 88 88 74 93 43 53 42 90 62 43 41 82 54 87
 90 96 25 35 17 84] 
 --------------------

b looks like
 -------------------- 
 [[[77 86 23 38 32]
  [86 75 71 64  1]
  [88 88 74 93 43]]

 [[53 42 90 62 43]
  [41 82 54 87 90]
  [96 25 35 17 84]]] 
 --------------------

c looks like
 -------------------- 
 [[77 86 23 38 32]
 [86 75 71 64  1]
 [88 88 74 93 43]
 [53 42 90 62 43]
 [41 82 54 87 90]
 [96 25 35 17 84]] 
 --------------------

Vector of random integers
 -------------------------------------------------- 
 [34 83  1 11 74 32 84 22 72 29]

Here is the sorted vector
 -------------------------------------------------- 
 [ 1 11 22 29 32 34 72 74 83 84]

5x5 Matrix of random integers
 -------------------------------------------------- 
 [[60 13  1 96 30]
 [14 20 98 39 64]
 [68 78 39 52 16]
 [48 56 77 24 42]
 [ 2 58 87 97 54]]

Here is the sorted matrix along eac

In [16]:
print("Max of a:", a.max())
print("Max of b:", b.max())
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a: 96
Max of b: 96
Max of a location: 25
Max of b location: 25
Max of c location: 25


## 5. Indexing and Slicing

Accessing elements or subsets of elements in NumPy arrays is fundamental. This section demonstrates various methods of indexing (single element, range, boolean, fancy indexing) and slicing (extracting sub-arrays).

In [ ]:
import numpy as np
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5) # Reshape 'a' into a 3D array (2 'slices', 3 rows, 5 columns)
c = a.reshape(6,5) # Reshape 'a' into a 2D array (6 rows, 5 columns)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)

A = ri(1,100,10) # Vector of random integers
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort')) # Sorts the 1D array

M = ri(1,100,25).reshape(5,5) # Matrix of random integers
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1 (sorts rows)
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort')) # Sorts columns (axis=0)

print("Max of a:", a.max()) # Maximum value in array 'a'
print("Max of b:", b.max()) # Maximum value in array 'b'
print("Max of a location:", a.argmax()) # Index of the maximum value in flattened array 'a'
print("Max of b location:", b.argmax()) # Index of the maximum value in flattened array 'b'
print("Max of c location:", b.argmax()) # This was a typo, should be c.argmax() for c, but demonstrates argmax on b

In [17]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [18]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[85 85 81 53 81]
 [73 44 13 97 63]
 [33 25 86 28 97]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 13

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 13

Row or column extract
----------------------
Entire row at index 2: [33 25 86 28 97]
Entire column at index 3: [53 97 28]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[97 63]
 [28 97]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[85 53]
 [44 97]]


## 6. Arithmetic Operations

NumPy arrays support element-wise arithmetic operations, making it easy to perform calculations on entire arrays without explicit loops.

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6]) # Slicing from index 3 up to (but not including) 6
print("Elements up to 4th index are:", arr[:4]) # Slicing from the beginning up to (but not including) 4
print("Elements from last backwards are:", arr[-1::-1]) # Reverse the array
print("3 Elements from last backwards are:", arr[-1:-6:-2]) # Every second element from the end, starting at the last

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Fancy indexing: selecting elements at specific indices

mat = np.array(ri(10,100,15)).reshape(3,5) # Create a 3x5 matrix of random 2-digit numbers
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2]) # Traditional Python list-of-lists indexing

print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2]) # NumPy's preferred and more efficient indexing
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2]) # Extracting a full row
print("Entire column at index 3:", mat[:,3]) # Extracting a full column (all rows, column index 3)

print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5]) # Slicing rows and columns to get a sub-matrix
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]]) # Combining slicing for rows and fancy indexing for columns

In [19]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[9 2 6]
 [4 3 4]
 [7 5 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 9 9]
 [5 5 3]
 [4 7 9]]

Addition
------------------
 [[16 11 15]
 [ 9  8  7]
 [11 12 18]]

Multiplication
------------------
 [[63 18 54]
 [20 15 12]
 [28 35 81]]

Division
------------------
 [[1.28571429 0.22222222 0.66666667]
 [0.8        0.6        1.33333333]
 [1.75       0.71428571 1.        ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[ 13 -12   0]
 [  2  -1   6]
 [ 13   1   9]]

Addition of a scalar (100)
-------------------------
 [[109 102 106]
 [104 103 104]
 [107 105 109]]

Exponentiation, matrix cubed here
----------------------------------------
 [[729   8 216]
 [ 64  27  64]
 [343 125 729]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[3.         1.41421356 2.44948974]
 [2.         1.73205081 2.        ]
 

## 7. Broadcasting

Broadcasting is a powerful feature in NumPy that allows arithmetic operations to be performed on arrays of different shapes. It automatically 'stretches' smaller arrays to match the shape of larger arrays during operations, provided certain compatibility rules are met.

For more detailed information, refer to the NumPy documentation on broadcasting: [https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n", mat1+mat2) # Element-wise addition
print("\nMultiplication\n------------------\n", mat1*mat2) # Element-wise multiplication
print("\nDivision\n------------------\n", mat1/mat2) # Element-wise division
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2) # Scalar multiplication and subtraction

print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1) # Scalar addition (broadcasts to all elements)

print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3) # Element-wise exponentiation
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5)) # Element-wise square root

**Broadcasting (super cool feature)**
NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

they are equal, or
one of them is 1
If these conditions are not met, a ValueError: frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

For more detail, please look up: https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [20]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [22]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [23]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [24]:
# add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [25]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])
print(start+add_scalar)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


## 8. Linear Algebra Operations

NumPy is a powerful tool for linear algebra, providing functions for dot products, inner/outer products, transposing matrices, calculating the trace, eigenvalues, and solving linear equations.

In [ ]:
start = np.zeros((4,3)) # A 4x3 matrix of zeros
print(start)

# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T # Transpose to make it a column vector
print(add_cols)

# add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

# this will just broadcast in both dimensions
add_scalar = np.array([100])
print(start+add_scalar) # Adding a scalar broadcasts it to every element

# Linear Algebra Operations
# Dot/Inner/Outer products

In [26]:
A = np.arange(1,10).reshape(3,3)
B = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of 1-9 single-digit numbers (A)\n","-"*50,"\n",A)
print("\n2nd Matrix of random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nDot product of A and B (for 2D arrays it is equivalent to matrix multiplication) \n","-"*80,"\n",np.dot(A,B))

A = np.arange(1,6)
B = ri(1,10,5)
print("\n1st Vector of 1-5 numbers (A)\n","-"*50,"\n",A)
print("\n2nd Vector of 5 random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nInner product of vectors A and B \n","-"*50,"\n",np.inner(A,B), "(sum of all pairwise elements)")
print("\nOuter product of vectors A and B \n","-"*50,"\n",np.outer(A,B))


1st Matrix of 1-9 single-digit numbers (A)
 -------------------------------------------------- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers (B)
 -------------------------------------------------- 
 [[8 1 2]
 [2 2 2]
 [7 6 9]]

Dot product of A and B (for 2D arrays it is equivalent to matrix multiplication) 
 -------------------------------------------------------------------------------- 
 [[ 33  23  33]
 [ 84  50  72]
 [135  77 111]]

1st Vector of 1-5 numbers (A)
 -------------------------------------------------- 
 [1 2 3 4 5]

2nd Vector of 5 random single-digit numbers (B)
 -------------------------------------------------- 
 [5 3 9 9 4]

Inner product of vectors A and B 
 -------------------------------------------------- 
 94 (sum of all pairwise elements)

Outer product of vectors A and B 
 -------------------------------------------------- 
 [[ 5  3  9  9  4]
 [10  6 18 18  8]
 [15  9 27 27 12]
 [20 12 36 36 16]
 [25 15 45 45 20]]


### 8.1 Transpose

The transpose of a matrix is obtained by changing its rows into columns and its columns into rows.

In [ ]:
A = np.arange(1,10).reshape(3,3) # Matrix A with elements 1 to 9
B = ri(1,10,9).reshape(3,3) # Matrix B with random single-digit numbers
print("\n1st Matrix of 1-9 single-digit numbers (A)\n","-"*50,"\n",A)
print("\n2nd Matrix of random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nDot product of A and B (for 2D arrays it is equivalent to matrix multiplication) \n","-"*80,"\n",np.dot(A,B)) # Matrix multiplication

A = np.arange(1,6) # Vector A with elements 1 to 5
B = ri(1,10,5) # Vector B with 5 random single-digit numbers
print("\n1st Vector of 1-5 numbers (A)\n","-"*50,"\n",A)
print("\n2nd Vector of 5 random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nInner product of vectors A and B \n","-"*50,"\n",np.inner(A,B), "(sum of all pairwise elements)") # Inner product
print("\nOuter product of vectors A and B \n","-"*50,"\n",np.outer(A,B)) # Outer product

# TRANSPOSE

In [27]:
A = ri(1,10,9).reshape(3,3)
print("\n3x3 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix transpose\n","-"*50,"\n",np.transpose(A))

B = ri(1,10,6).reshape(3,2)
print("\n3x2 Matrix of random single-digit numbers\n","-"*50,"\n",B)
print("\n2x3 Matrix transpose\n","-"*50,"\n",np.transpose(B))
print("\nMatrix multiplication of B and B-transpose\n","-"*50,"\n",np.dot(B, np.transpose(B)))


3x3 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 9 1]
 [2 2 7]
 [9 9 7]]

Matrix transpose
 -------------------------------------------------- 
 [[5 2 9]
 [9 2 9]
 [1 7 7]]

3x2 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 5]
 [6 1]
 [7 9]]

2x3 Matrix transpose
 -------------------------------------------------- 
 [[5 6 7]
 [5 1 9]]

Matrix multiplication of B and B-transpose
 -------------------------------------------------- 
 [[ 50  35  80]
 [ 35  37  51]
 [ 80  51 130]]


### 8.2 Matrix Trace

The trace of a square matrix is the sum of the elements on its main diagonal. NumPy's `np.trace` function can also compute the sum along other diagonals using an offset.

In [ ]:
A = ri(1,10,9).reshape(3,3) # Create a 3x3 matrix
print("\n3x3 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix transpose\n","-"*50,"\n",np.transpose(A)) # Transpose of matrix A

B = ri(1,10,6).reshape(3,2) # Create a 3x2 matrix
print("\n3x2 Matrix of random single-digit numbers\n","-"*50,"\n",B)
print("\n2x3 Matrix transpose\n","-"*50,"\n",np.transpose(B)) # Transpose of matrix B
print("\nMatrix multiplication of B and B-transpose\n","-"*50,"\n",np.dot(B, np.transpose(B))) # Example of multiplying a matrix by its transpose

In [28]:
A = ri(1,10,16).reshape(4,4)
print("\n4x4 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix trace\n","-"*50,"\n",np.trace(A))
print("\nMatrix trace with ofset +1 (upper triangle)\n","-"*50,"\n",np.trace(A,offset=1))
print("\nMatrix trace with ofset -1 (lower triangle)\n","-"*50,"\n",np.trace(A,offset=-1))


4x4 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 9 4 2]
 [2 5 3 8]
 [6 8 6 6]
 [4 8 9 4]]

Matrix trace
 -------------------------------------------------- 
 19

Matrix trace with ofset +1 (upper triangle)
 -------------------------------------------------- 
 18

Matrix trace with ofset -1 (lower triangle)
 -------------------------------------------------- 
 19


### 8.3 Eigenvalues and Eigenvectors

Eigenvalues and eigenvectors are crucial in many areas of linear algebra, physics, and engineering. They describe the directions along which a linear transformation acts by scaling only.

In [ ]:
A = ri(1,10,16).reshape(4,4) # Create a 4x4 matrix
print("\n4x4 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix trace\n","-"*50,"\n",np.trace(A)) # Sum of elements on the main diagonal (offset=0)
print("\nMatrix trace with offset +1 (upper triangle)\n","-"*50,"\n",np.trace(A,offset=1)) # Sum of elements on the diagonal above the main diagonal
print("\nMatrix trace with offset -1 (lower triangle)\n","-"*50,"\n",np.trace(A,offset=-1)) # Sum of elements on the diagonal below the main diagonal

# **Eigenvalues and eigenvectors**

In [29]:
A = np.random.randn(9).reshape(3,3)
print("Original matrix\n",A)
print("\n")
w,v=np.linalg.eig(A)
print("Eigenvalues:\n",w)
print("\n")
print("Eigenvectors:\n",v)

Original matrix
 [[ 0.35861775 -0.38724652 -0.98647316]
 [ 1.64196054  1.09290686 -1.50120571]
 [-0.01499294  1.58894019 -0.81344593]]


Eigenvalues:
 [ 0.70771918+1.67839708j  0.70771918-1.67839708j -0.77735969+0.j        ]


Eigenvectors:
 [[-0.1427593 -0.40387417j -0.1427593 +0.40387417j  0.66000893+0.j        ]
 [-0.7401936 +0.j         -0.7401936 -0.j          0.02328125+0.j        ]
 [-0.34606756+0.38581876j -0.34606756-0.38581876j  0.75089693+0.j        ]]


### 8.4 Linear Equation Solving and Matrix Inverse

NumPy's `np.linalg.solve` function allows direct solution of systems of linear equations, and `np.linalg.inv` can compute the inverse of a matrix.

In [ ]:
A = np.random.randn(9).reshape(3,3) # Create a 3x3 matrix with random numbers from a standard normal distribution
print("Original matrix\n",A)
print("\n")
w,v=np.linalg.eig(A) # Compute eigenvalues (w) and eigenvectors (v)
print("Eigenvalues:\n",w)
print("\n")
print("Eigenvectors:\n",v)

# Linear equation solving, matrix inverse, linear least suqare
You can directly solve linear system of equations using NumPy writing only one line of code.

Suppose you want to solve the following set of equations for (x,y,z). It is easy to see that (2,1,5) are the unique solutions.

2x + 5y + z = 14;

3x - 2y - z = -1;

x - 3y + z = 4

In [30]:
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]])
B = np.array([14,-1,4])
x = np.linalg.solve(A,B)

print("The solutions are:",x)

The solutions are: [2. 1. 5.]


## 9. Additional Reshaping Example

This final example demonstrates another use case for reshaping a 1D array into a 2D column vector.

In [ ]:
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]]) # Coefficient matrix
B = np.array([14,-1,4]) # Result vector
x = np.linalg.solve(A,B) # Solve the linear system Ax = B for x

print("The solutions are:",x)

In [31]:
x=[1,2,3]
import numpy as np
x= np.array(x)
x.reshape(3, -1)

array([[1],
       [2],
       [3]])

In [ ]:
x=[1,2,3]
import numpy as np # Import numpy if not already imported in this scope
x= np.array(x)
x.reshape(3, -1) # Reshape the 1D array into a 2D array with 3 rows and automatically determined columns (-1)